---

- src: calvinbui.ansible_docker
  version: '1.1'

- src: calvinbui.ansible_docker_network
  version: '1.0.0'

- src: calvinbui.ansible_pip
  version: '2.0.0'

- src: calvinbui.ansible_postgres_docker
  version: '2.0.0'

- src: calvinbui.ansible_confluence_docker
  version: '2.0.0'

- src: calvinbui.ansible_acme_certificates
  version: '1.4.0'
